apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:8.0.7-fpm
        imagePullPolicy: Never
        volumeMounts:
        - name: code-dir-pv
          mountPath: /var/www/html
      volumes:
      - name: code-dir-pv
        persistentVolumeClaim:
          claimName: code-dir-pv-claim

